### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sayandedotcom** [0mn1core/express-typescript-vercel-template#1]
I have cloned your project and just removed the .github folder ( CI/CD .. is it necessary) and getting this error?? why. any configuration in vercel ??

![image](https://github.com/user-attachments/assets/98c9b08f-3929-45c9-9a42-ff5cd03327b6)

**Comment by 0mn1core** [comment]
Woah, wasn't actually expecting anyone to find this randomly, was gonna eventually write up documentation and post to vercel.community. But yes, in your Vercel project, go to Settings > General, and under the section "Build & Development Settings", turn on the override for "Output Directory" and set it to `./`. Not sure why it needs that, as it says the default behavior is to check both `root` and the `public` folder, but when I was cleaning up from my attempts at the Vercel Github integration, removing that portion caused the error you were seeing.

If you don't mind me asking, how'd you find the project? Also what are you attempting to make? Trying to make this into a template repo to assist people getting started in the future, and would definitely love to know what people are interested in using it for to see what else I can add that might help code or documentation wise.

Are you just planning on deploying from the Vercel CLI everytime?

**Comment by sayandedotcom** [comment]
Waiting for the documentation ! It's still not working even after changing the "Output Directory" . I am not deploying with cli but from platform.. help me plzz. stucked with my side hustle for this !!
![image](https://github.com/user-attachments/assets/b32d3700-4ee8-49ec-892e-f0228643f7e9)
repo -> https://github.com/sayandedotcom/express-typescript-vercel-template

I searched on GitHub "express vercel deploy" and filtered with recently updated and I found this repo with a live link !!

**Comment by 0mn1core** [comment]
From which platform, Vercel or Github? You can't launch a deployment from Vercel since it's a typescript project that needs to be built, and Vercel doesn't know anything about that. If you give it a build command and tell it about that, then that breaks Vercel's ability to auto detect the framework for some reason.

Checking out your project, it looks like you're going back to the git workflows, but your build failed because you didn't have the secrets it uses set. Follow this [documentation from Vercel](https://vercel.com/guides/how-can-i-use-github-actions-with-vercel#configuring-github-actions-for-vercel) to get the secrets, then in your Github project, go to "Settings" > "Secrets and variables" > "actions" and add those secrets to the repo so that the CI/CD can use them.

**Comment by 0mn1core** [comment]
Looks like you've successfully built and deployed, good if I close this issue?

**Comment by sayandedotcom** [comment]
yup !! do you have any social acc.. eg- twitter.. id?

**Comment by 0mn1core** [comment]
Yup, but don't post too much @0mn1core on twitter.
